name: GoLang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }} //Sonar Token generated 
        login: ${{ secrets.SONARQUBE_TOKEN }} example URL (https://sonarqube.xhilmi.co.id)
        
  build-push:
    name: Build and Push
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/cicd-golang:${{ github.ref_name }}"
